# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadingUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Loading_win(object):
    def setupUi(self, Loading_win):
        Loading_win.setObjectName("Loading_win")
        Loading_win.resize(508, 137)
        self.verticalLayout = QtWidgets.QVBoxLayout(Loading_win)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Loading_win)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Loading_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(Loading_win)
        QtCore.QMetaObject.connectSlotsByName(Loading_win)

    def retranslateUi(self, Loading_win):
        _translate = QtCore.QCoreApplication.translate
        Loading_win.setWindowTitle(_translate("Loading_win", "正在加载视频流"))
        self.label_2.setText(_translate("Loading_win", "加载视频流中..."))
